
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

// Load env vars
dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('❌ Missing Environment Variables');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function verifyRecoverySystem() {
    console.log('🚀 Starting Recovery System Verification (Sprint 13)...');

    try {
        // 1. Check Table
        console.log('\n🔍 Step 1: Checking Table Existence...');
        const { count, error: tableError } = await supabase
            .from('registros_recuperacion')
            .select('*', { count: 'exact', head: true });

        if (tableError) throw new Error(`Table Check Failed: ${tableError.message}`);
        console.log(`✅ Table 'registros_recuperacion' exists (Rows: ${count})`);

        // 2. Get a User
        const { data: users } = await supabase.from('perfiles').select('id').limit(1);
        const userId = users?.[0]?.id;

        if (!userId) {
            throw new Error('❌ Need at least one user in "perfiles" to test Recovery Logs.');
        }
        console.log(`✅ Using Test User ID: ${userId}`);

        // 3. Insert Recovery Log
        console.log('\n📝 Step 2: Inserting Test Log...');
        const testLog = {
            usuario_id: userId,
            fecha: new Date().toISOString().split('T')[0], // YYYY-MM-DD
            horas_sueno: 7.5,
            calidad_sueno: 8,
            nivel_estres: 3,
            nivel_fatiga: 4,
            notas: 'Test generated by check-recovery-data.ts'
        };

        const { data: inserted, error: insertError } = await supabase
            .from('registros_recuperacion')
            .insert(testLog)
            .select()
            .single();

        if (insertError) {
            // Handle constraint violations (duplicate date for user)
            if (insertError.code === '23505') {
                console.log('⚠️ Log already exists for today. Trying to read it...');
            } else {
                throw insertError;
            }
        } else {
            console.log(`✅ Log Inserted: ID ${inserted.id}`);
        }

        // 4. Read Verification
        console.log('\n📖 Step 3: Verifying Read Access...');
        const { data: logs, error: readError } = await supabase
            .from('registros_recuperacion')
            .select('*')
            .eq('usuario_id', userId)
            .limit(1);

        if (readError) throw readError;

        if (logs && logs.length > 0) {
            console.log('✅ Read Successful. Data:', JSON.stringify(logs[0], null, 2));
        } else {
            throw new Error('❌ Insert appeared successful but Read returned no data (Possible Policies issue?)');
        }

        // 5. Cleanup
        if (inserted) {
            await supabase.from('registros_recuperacion').delete().eq('id', inserted.id);
            console.log('✅ Cleanup done.');
        }

        console.log('\n🎉 RECOVERY SYSTEM VERIFIED SUCCESSFULLY!');

    } catch (error: any) {
        console.error('\n❌ VERIFICATION FAILED:', error.message);
        process.exit(1);
    }
}

verifyRecoverySystem();
